### ISSUE TITLE
BackupPC::XS build under aarch64 and ppc64le

### ISSUE THREAD

**Issue by dfateyev** [backuppc/backuppc-xs#2]
We experience build issues under `aarch64` and `ppc64le` architectures in Fedora and RHEL:
```
./configure.sh
configure.sh: Configuring rsync 3.0.9
checking build system type... ./config.guess: unable to guess system type
This script, last modified 2006-07-02, has failed to recognize
the operating system you are using. It is advised that you
download the most up to date version of the config scripts from
  http://savannah.gnu.org/cgi-bin/viewcvs/*checkout*/config/config/config.guess
and
  http://savannah.gnu.org/cgi-bin/viewcvs/*checkout*/config/config/config.sub
If the version you run (./config.guess) is already up to date, please
send the following data and any information you think might be
pertinent to <config-patches@gnu.org> in order to provide the needed
information to handle your system.
config.guess timestamp = 2006-07-02
uname -m = aarch64
uname -r = 4.9.4-201.fc25.aarch64
uname -s = Linux
uname -v = #1 SMP Mon Jan 23 03:05:11 UTC 2017
/usr/bin/uname -p = aarch64
/bin/uname -X     = 
hostinfo               = 
/bin/universe          = 
/usr/bin/arch -k       = 
/bin/arch              = aarch64
/usr/bin/oslevel       = 
/usr/convex/getsysinfo = 
UNAME_MACHINE = aarch64
UNAME_RELEASE = 4.9.4-201.fc25.aarch64
UNAME_SYSTEM  = Linux
UNAME_VERSION = #1 SMP Mon Jan 23 03:05:11 UTC 2017
configure.sh: error: cannot guess build type; you must specify one
make: *** [config.h] Error 1
```
Full build logs are available here: [18285394](https://kojipkgs.fedoraproject.org//work/tasks/5394/18285394/build.log), [18285377](https://kojipkgs.fedoraproject.org//work/tasks/5377/18285377/build.log)

**Comment by craigbarratt** [comment]
Thanks for the report.  I need to update config.guess and config.sub.  Is
there a way to send you a candidate BackupPC-XS-0.52.tar.gz to confirm the
fix works before I release it?

Craig

**Comment by dfateyev** [comment]
You can send me the tarball or a link by email (shown in Github profile).
Or, you can push changes to this repo, so I could grab them and try to build.

**Comment by craigbarratt** [comment]
Denis,

I've pushed new versions of config.guess and config.sub (
https://github.com/backuppc/backuppc-xs/commit/d394e556bfbbf254f227bb4084104932261f740e
)

I separately bumped the version to 0.52 (
https://github.com/backuppc/backuppc-xs/commit/90d9166cdbc284f6d48658d47bc46c15d798f966
).

So you can pull the latest, or
just d394e556bfbbf254f227bb4084104932261f740e.

Craig

**Comment by dfateyev** [comment]
Thanks for the fix, Craig. Now, it's built without issues.
